//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由导表工具生成。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Config
{
    public static class ConfigKit
    {
        public static void LoadAll(Func<string, byte[]> dataLoader)
        {
            LoadLanguage(dataLoader);
        }

        public static async Task LoadAllAsync(Func<string, Task<byte[]>> dataLoader)
        {
            var tasks = new List<Task>();
            tasks.Add(LoadLanguageAsync(dataLoader));
            await Task.WhenAll(tasks);
        }

        public static void UnloadAll()
        {
            UnloadLanguage();
        }

        public static void LoadTable(string tableName, Func<string, byte[]> dataLoader)
        {
            switch (tableName)
            {
                case "Language":
                    LoadLanguage(dataLoader);
                    break;
                default:
                    throw new Exception($"Unknown table: {tableName}");
            }
        }

        public static void UnloadTable(string tableName)
        {
            switch (tableName)
            {
                case "Language":
                    UnloadLanguage();
                    break;
            }
        }

        public static void LoadLanguage(Func<string, byte[]> dataLoader)
        {
            var data = dataLoader("Language");
            LanguageCategory.Initialize(data);
        }

        public static async Task LoadLanguageAsync(Func<string, Task<byte[]>> dataLoader)
        {
            var data = await dataLoader("Language");
            LanguageCategory.Initialize(data);
        }

        public static void UnloadLanguage()
        {
            LanguageCategory.Clear();
        }
    }

    public static class ConfigReader
    {
        public static int Readint(BinaryReader reader) => reader.ReadInt32();
        public static uint Readuint(BinaryReader reader) => reader.ReadUInt32();
        public static float Readfloat(BinaryReader reader) => reader.ReadSingle();
        public static bool Readbool(BinaryReader reader) => reader.ReadByte() == 1;
        public static long Readlong(BinaryReader reader) => reader.ReadInt64();
        public static string Readstring(BinaryReader reader) {
            int len = reader.ReadInt32();
            return System.Text.Encoding.UTF8.GetString(reader.ReadBytes(len));
        }

        public static T[] ReadArray<T>(BinaryReader reader, Func<BinaryReader, T> readElem) {
            int len = reader.ReadInt32();
            if (len == 0) return Array.Empty<T>();
            var arr = new T[len];
            for (int i = 0; i < len; i++) arr[i] = readElem(reader);
            return arr;
        }

        public static int[] Readint_arr(BinaryReader reader) => ReadArray(reader, Readint);
        public static uint[] Readuint_arr(BinaryReader reader) => ReadArray(reader, Readuint);
        public static float[] Readfloat_arr(BinaryReader reader) => ReadArray(reader, Readfloat);
        public static bool[] Readbool_arr(BinaryReader reader) => ReadArray(reader, Readbool);
        public static string[] Readstring_arr(BinaryReader reader) => ReadArray(reader, Readstring);

        public static T[][] ReadArray2D<T>(BinaryReader reader, Func<BinaryReader, T[]> readArr) {
            int len = reader.ReadInt32();
            if (len == 0) return Array.Empty<T[]>();
            var arr = new T[len][];
            for (int i = 0; i < len; i++) arr[i] = readArr(reader);
            return arr;
        }

        public static int[][] Readint_arr2(BinaryReader reader) => ReadArray2D(reader, Readint_arr);
        public static uint[][] Readuint_arr2(BinaryReader reader) => ReadArray2D(reader, Readuint_arr);
        public static float[][] Readfloat_arr2(BinaryReader reader) => ReadArray2D(reader, Readfloat_arr);
        public static bool[][] Readbool_arr2(BinaryReader reader) => ReadArray2D(reader, Readbool_arr);
        public static string[][] Readstring_arr2(BinaryReader reader) => ReadArray2D(reader, Readstring_arr);
    }
}
