//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由导表工具生成。
//     表格名称: Language
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Config
{
    /// <summary>
    /// Language 表定义
    /// </summary>
    public class LanguageTable
    {
        /// <summary>
        /// 道具ID
        /// </summary>
        public long ID { get; set; }
        /// <summary>
        /// 简体中文
        /// </summary>
        public string ZhCn { get; set; }
        /// <summary>
        /// 美国
        /// </summary>
        public string EnUs { get; set; }
        public const long Test1 = 10001;
        public const long Test2 = 10002;
        public const long Test3 = 10003;
        public const long Test4 = 10004;
        public const long Test5 = 10005;
        public const long Test6 = 10006;
        public const long Test7 = 10007;
        public const long Test8 = 10008;
        public const long Test9 = 10009;
        public const long Test10 = 10010;
    }

    public static class LanguageCategory
    {
        public static List<LanguageTable> All = new List<LanguageTable>();
        public static Dictionary<long, LanguageTable> DataMap = new Dictionary<long, LanguageTable>();

        public static void Initialize(byte[] data)
        {
            using (var ms = new MemoryStream(data))
            using (var reader = new BinaryReader(ms))
            {
                int count = reader.ReadInt32();
                All = new List<LanguageTable>(count);
                DataMap = new Dictionary<long, LanguageTable>(count);
                for (int i = 0; i < count; i++)
                {
                    var row = new LanguageTable();
                    row.ID = ConfigReader.Readlong(reader);
                    row.ZhCn = ConfigReader.Readstring(reader);
                    row.EnUs = ConfigReader.Readstring(reader);
                    All.Add(row);
                    DataMap[row.ID] = row;
                }
            }
        }

        public static void Clear()
        {
            All.Clear();
            DataMap.Clear();
        }
    }
}